openapi: 3.0.0
info:
  title: CRUD API
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: CRUD methods api
    description: API для операций CRUD с продуктами
paths:
  /api/product/{id}:
    get:
      tags:
        - CRUD methods api
      summary: Получить продукт по ID
      description: Получение продукта по его идентификатору.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Идентификатор продукта.
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Продукт не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/product/all:
    get:
      tags:
        - CRUD methods api
      summary: Получить все продукты
      description: Получение списка всех продуктов.
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Не удалось получить продукты
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/product/delete/{id}:
    delete:
      tags:
        - CRUD methods api
      summary: Удалить продукт по ID
      description: Удаление продукта по его идентификатору.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Идентификатор продукта.
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: string
                example: "Продукт удален"
        '400':
          description: Ошибка при удалении продукта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Продукт не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/product/create:
    post:
      tags:
        - CRUD methods api
      summary: Добавить новый продукт
      description: Добавление нового продукта.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: string
                example: "Продукт добавлен"
        '400':
          description: Не удалось добавить продукт.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Продукт с таким артикулом уже существует."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/product/update/{id}:
    put:
      tags:
        - CRUD methods api
      summary: Обновить продукт по ID
      description: Обновление продукта по его идентификатору.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Идентификатор продукта.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: string
                example: "Продукт обновлен"
        '400':
          description: Ошибка при обновлении продукта с id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Продукт не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Продукт с таким артикулом уже существует."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор продукта.
        name:
          type: string
          description: Название продукта.
        articular:
          type: string
          description: Уникальный идентификатор продукта.
        description:
          type: string
          description: Описание продукта.
        category:
          type: string
          description: Категория продукта.
        cost:
          type: number
          format: double
          description: Стоимость продукта.
        amount:
          type: integer
          description: Количество продукта.
        created:
          type: string
          format: date-time
          description: Метка времени создания продукта.
        updatedOn:
          type: string
          format: date-time
          description: Метка времени последнего обновления продукта (Меняется только при обновлении количества).

    ProductRequest:
      type: object
      properties:
        name:
          type: string
          description: Название продукта.
        articular:
          type: string
          description: Уникальный идентификатор продукта.
        description:
          type: string
          description: Описание продукта.
        category:
          type: string
          description: Категория продукта.
        cost:
          type: number
          format: double
          description: Стоимость продукта.
        amount:
          type: integer
          description: Количество продукта.

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          description: Код состояния HTTP.
        message:
          type: string
          description: Текст сообщения об ошибке.
        timestamp:
          type: string
          format: date-time
          description: Временная метка ошибки.
